name: macOS RDP
on: workflow_dispatch

jobs:
  mac-rdp:
    runs-on: macos-latest
    steps:
      - name: Install and Connect Tailscale
        run: |
          # Mac par Tailscale install kar rahe hain
          brew install tailscale
          
          # Background mein Tailscale service start kar rahe hain
          sudo tailscaled > /dev/null 2>&1 &
          sleep 5
          
          # Authkey se login kar rahe hain
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=mac-rdp-runner

      - name: Start Screen Sharing (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvnclegacy -vnclegacy yes -clientopts -setvncpw -vncpw 123456 -restart -agent -privs -all
          echo "Screen sharing started. VNC Password is: 123456"

      - name: Keep Server Running
        run: sleep 6h
